name: Terraform Validate and Plan (No Apply)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      
      - name: Terraform Init (no backend)
        run: terraform init -backend=false -reconfigure -input=false

      - name: Terraform Format check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan (simulation, no backend)
        run: terraform plan -lock=false -input=false -no-color
        continue-on-error: true
